# Generated by Django 4.1.7 on 2023-09-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_alter_contact_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
